/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.6
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "memcached slo benchmark"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "memcached slo benchmark"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "1.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  char ** server_arg;	/**< @brief Memcached server hostname[:port].  Repeat to specify multiple servers..  */
  char ** server_orig;	/**< @brief Memcached server hostname[:port].  Repeat to specify multiple servers. original value given at command line.  */
  unsigned int server_min; /**< @brief Memcached server hostname[:port].  Repeat to specify multiple servers.'s minimum occurreces */
  unsigned int server_max; /**< @brief Memcached server hostname[:port].  Repeat to specify multiple servers.'s maximum occurreces */
  const char *server_help; /**< @brief Memcached server hostname[:port].  Repeat to specify multiple servers. help description.  */
  int time_arg;	/**< @brief Maximum time to run (seconds). (default='5').  */
  char * time_orig;	/**< @brief Maximum time to run (seconds). original value given at command line.  */
  const char *time_help; /**< @brief Maximum time to run (seconds). help description.  */
  int keysize_arg;	/**< @brief Length of memcached keys. (default='30').  */
  char * keysize_orig;	/**< @brief Length of memcached keys. original value given at command line.  */
  const char *keysize_help; /**< @brief Length of memcached keys. help description.  */
  int valuesize_arg;	/**< @brief Length of memcached values. (default='200').  */
  char * valuesize_orig;	/**< @brief Length of memcached values. original value given at command line.  */
  const char *valuesize_help; /**< @brief Length of memcached values. help description.  */
  int records_arg;	/**< @brief Number of memcached records to use.  If multiple memcached servers are given, this number is divided by the number of servers. (default='10000').  */
  char * records_orig;	/**< @brief Number of memcached records to use.  If multiple memcached servers are given, this number is divided by the number of servers. original value given at command line.  */
  const char *records_help; /**< @brief Number of memcached records to use.  If multiple memcached servers are given, this number is divided by the number of servers. help description.  */
  float ratio_arg;	/**< @brief Ratio of set/get commands. (default='0.0').  */
  char * ratio_orig;	/**< @brief Ratio of set/get commands. original value given at command line.  */
  const char *ratio_help; /**< @brief Ratio of set/get commands. help description.  */
  int connections_arg;	/**< @brief Connections to establish per server. (default='1').  */
  char * connections_orig;	/**< @brief Connections to establish per server. original value given at command line.  */
  const char *connections_help; /**< @brief Connections to establish per server. help description.  */
  int depth_arg;	/**< @brief Maximum depth to pipeline requests. (default='1').  */
  char * depth_orig;	/**< @brief Maximum depth to pipeline requests. original value given at command line.  */
  const char *depth_help; /**< @brief Maximum depth to pipeline requests. help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int server_given ;	/**< @brief Whether server was given.  */
  unsigned int time_given ;	/**< @brief Whether time was given.  */
  unsigned int keysize_given ;	/**< @brief Whether keysize was given.  */
  unsigned int valuesize_given ;	/**< @brief Whether valuesize was given.  */
  unsigned int records_given ;	/**< @brief Whether records was given.  */
  unsigned int ratio_given ;	/**< @brief Whether ratio was given.  */
  unsigned int connections_given ;	/**< @brief Whether connections was given.  */
  unsigned int depth_given ;	/**< @brief Whether depth was given.  */

} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief the description string of the program */
extern const char *gengetopt_args_info_description;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char **argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char **argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
